# Generated by Django 4.1.5 on 2023-02-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('efecto', models.CharField(max_length=50)),
                ('unidades', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedalclon',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='PedalPropio',
        ),
        migrations.RemoveField(
            model_name='pedalreparar',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='PedalClon',
        ),
        migrations.DeleteModel(
            name='PedalReparar',
        ),
    ]
