# Generated by Django 4.1.5 on 2023-02-07 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_stockpropio_remove_pedalclon_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedalReparar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('efecto', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('volts', models.IntegerField()),
                ('made', models.CharField(max_length=50)),
                ('presupuesto', models.IntegerField()),
                ('envio', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.cliente')),
            ],
        ),
    ]
