# Generated by Django 4.1.5 on 2023-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_pedalreparar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='pedal@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='pedalreparar',
            name='envio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedalreparar',
            name='volts',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockpropio',
            name='precio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockpropio',
            name='unidades',
            field=models.CharField(max_length=20),
        ),
    ]
