# Generated by Django 4.1.5 on 2023-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_pedalreparar_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapropio',
            name='envio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventapropio',
            name='cantidad',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ventapropio',
            name='precio',
            field=models.IntegerField(default=None),
        ),
    ]
